name: Build and deploy Node.js app to Azure Web App - gabowebapptest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # O ajusta a la versión que uses en noderino

      - name: Install dependencies
        run: npm install

      - name: Optional - Build step
        run: npm run build || echo "No build step defined"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gabowebapptest'  # <-- Nombre exacto de tu Web App en Azure
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
